services:
  # ----- builders
  nuxtbuilder:
    image: public.ecr.aws/docker/library/node:20-bullseye-slim
    working_dir: /workdir
    user: 1000:1000
    volumes:
      - ./mahitotsu-ya-website/:/workdir:rw
    entrypoint: ['npm']
    command: ['run','build']
  # ----- runtimes
  website:
    image: public.ecr.aws/docker/library/node:20-bullseye-slim
    working_dir: /workdir
    init: true
    volumes:
      - ./mahitotsu-ya-website/.output:/workdir:ro
      - $HOME/.aws:/root/.aws:ro
    environment:
      - NUXT_CONTENTS_BUCKET_NAME=mahitotsuyastack-contentsbucket571b0902-qaeh4b9lrhtf
      - NUXT_CONTENTS_KEY_PREFIX=
    ports:
      - 3000:3000
    entrypoint: ['node']
    command: ['./server/index.mjs']
    depends_on:
      nuxtbuilder:
        condition: service_completed_successfully